### ISSUE TITLE
Not able to install pytorch on cuda version 10.0

### ISSUE THREAD

**Issue by umgpy** [FETS-AI/Front-End#20]
## Expected Behavior

Successful installation of PyTorch in the OpenFederatedLearning virtual environment.

## Actual Behavior

Error in installation even after meeting the cuda version requirement as stated in the document

> GPU: for faster training and inference
>  CUDA 9.2 - 10.2

Error thrown -
`nnunet 1.6.6 has requirement torch>=1.6.0a, but you'll have torch 1.4.0+cu100 which is incompatible.
gandlf 0.0.7.NR has requirement torch>=1.7, but you'll have torch 1.4.0+cu100 which is incompatible.
torchaudio 0.7.2 has requirement torch==1.7.1, but you'll have torch 1.4.0+cu100 which is incompatible.
`

## Steps to Reproduce the Problem

  1.  Cuda version 10.0
  2. Install PyTorch for the specific  cuda version

## Specifications

  - Cuda Version: 10.0
  - Platform: Ubuntu  18.04
 
Looking forward to resolving this issues,  please let me know if any more information is needed from my end.
Thanks

**Comment by sarthakpati** [comment]
Hi Umang,

Please install PyTorch on the virtual environment using the instructions in https://pytorch.org/get-started/locally/ before re-trying. PyTorch _should_ work across all CUDA versions.

**Comment by umgpy** [comment]
Hi Sarthak,

I checked the installed packages in the virtual environments python folder and found that torch, torchvision etc were already installed during the initial installation from the binary file. I believe due to this when I was installing PyTorch for my CUDA version it was giving me the warnings. In that case installation of PyTorch as directed in the doc, [https://fets-ai.github.io/Front-End/setup#set-up-the-environment](https://fets-ai.github.io/Front-End/setup#set-up-the-environment) should be updated to optional since the binary is installing it nonetheless.
I am closing this issue. 
Thanks for the help.
