### ISSUE TITLE
Better handling of dirrectories in SanityCheck  

### ISSUE THREAD

**Issue by umgpy** [FETS-AI/Front-End#42]
**Is your feature request related to a problem? Please describe.**
SanityCheck #22 fails with error when running script after running the FeTS_CLI in training mode.

**Describe the solution you'd like**
Add better handling for excluded directories in the input folder.

**Describe alternatives you've considered**
None

**Additional context**
Hi we added additional processed and corrected data to the already existing DataForFeTS folder. Upon running SanityCheck script I encountered this error.

>    Traceback (most recent call last):
>    File "./SanityCheck.py", line 197, in
>       main()
>      File "./SanityCheck.py", line 124, in main
>        first, *rest = files_for_subject.items() # split the dict>
>   ValueError: not enough values to unpack (expected at least 1, got 0)Going through the python script I don't see any reason to expect this error

This is due to the following line in #23 -
`for dirs in os.listdir(inputDir):`
`if dirs != 'logs': # don't perform sanity check for the 'logs' folder`

After removing split_info folder there were of course no issues, but it would be helpful if the script handled excluding the other folder too in case anyone is planning to add new data.

Thanks

**Comment by sarthakpati** [comment]
Hi @umgpy,

Can you try with the latest SanityCheck? I believe this has been fixed [[ref](https://github.com/FETS-AI/Front-End/blob/master/src/applications/SanityCheck.py#L136)].

**Comment by umgpy** [comment]
Hi @sarthakpati,

Yes going through the 0.0.5 release and running the updated script fixes it. Thanks a lot.
