### ISSUE TITLE
Inconsistent modality dict in SanityCheck.py and Phase2_IntensityCheck.py

### ISSUE THREAD

**Issue by MeiruiJiang** [FETS-AI/Front-End#48]
**Describe the bug**
The modality dict in Phase2_IntensityCheck.py(line 141) maps 'T1CE' to '_t1Gd.nii.gz' while in SanityCheck.py(line 125) maps 'T1CE' to '_t1ce.nii.gz', which may cause check failed due to different naming strategy.
I am not sure if it affects the model training.

Follow the FeTS documentation, we used 't1ce.nii.gz' for T1CE modality.

**Comment by sarthakpati** [comment]
Done, thank you!
