### ISSUE TITLE
Enquiry for installation

### ISSUE THREAD

**Issue by mirror1102** [FETS-AI/Front-End#76]
Dear developers,
 I would like to express my sincere gratitude for providing such commendable software. I noticed that there is an installation instruction for the Windows system, but I can not find any installation package for the Windows system. Would you be able to provide installation package for the Windows system and how to obtain it? Thanks!

**Comment by sarthakpati** [comment]
Hi,

Thank you for your interest in the FeTS Tool. The current mode of dissemination of this is through Docker containers. Please see this link for details: https://github.com/FeTS-AI/Front-End/pkgs/container/front-end

As an added note, here is a related link to help you get started with Dockers: https://devblogs.microsoft.com/premier-developer/getting-started-with-docker-for-windows/

Please free to respond to this issue if you have further questions! 

Cheers,
Sarthak
