### ISSUE TITLE
FetS-AI on cuda versions>10.2

### ISSUE THREAD

**Issue by archithrajan** [FETS-AI/Front-End#83]
Dear Experts,

Wanted to enquire if a later version of the installer would be compatible with cuda versions > 10.2.

Regards,
Archith

**Comment by sarthakpati** [comment]
Hi,

Thank you for your interest in the FeTS project! 

This project is no longer being actively developed or maintained. Please refer to our Docker builds: https://github.com/orgs/FeTS-AI/packages?repo_name=Front-End 

Cheers,
Sarthak
